before:
  hooks:
  - go mod download

builds:
  - id: "chain-maind-darwin-arm64"
    main: ./cmd/chain-maind
    binary: bin/chain-maind
    env:
      - CGO_ENABLED=1
      - SDKROOT=/Applications/Xcode_12.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk 
      - MACOSX_DEPLOYMENT_TARGET=11.0
    goos:
      - darwin
    goarch:
      - arm64
    flags:
        - -tags=cgo,ledger,!test_ledger_mock,!ledger_mock,!ledger_zemu
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=crypto-org-chain -X github.com/cosmos/cosmos-sdk/version.ServerName=chain-maind -X github.com/cosmos/cosmos-sdk/version.ClientName=chain-maincli -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
  
archives:
- name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: Darwin
    amd64: x86_64
  builds:
  - chain-maind-darwin-arm64
checksum:
  name_template: 'checksumsmac.txt'

