// source: tendermint/evidence/types.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var gogoproto_gogo_pb = require('../../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var tendermint_types_validator_pb = require('../../tendermint/types/validator_pb.js');
goog.object.extend(proto, tendermint_types_validator_pb);
var tendermint_types_evidence_pb = require('../../tendermint/types/evidence_pb.js');
goog.object.extend(proto, tendermint_types_evidence_pb);
goog.exportSymbol('proto.tendermint.evidence.Info', null, global);
goog.exportSymbol('proto.tendermint.evidence.List', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tendermint.evidence.List = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.tendermint.evidence.List.repeatedFields_, null);
};
goog.inherits(proto.tendermint.evidence.List, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tendermint.evidence.List.displayName = 'proto.tendermint.evidence.List';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tendermint.evidence.Info = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.tendermint.evidence.Info.repeatedFields_, null);
};
goog.inherits(proto.tendermint.evidence.Info, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tendermint.evidence.Info.displayName = 'proto.tendermint.evidence.Info';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.tendermint.evidence.List.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tendermint.evidence.List.prototype.toObject = function(opt_includeInstance) {
  return proto.tendermint.evidence.List.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tendermint.evidence.List} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tendermint.evidence.List.toObject = function(includeInstance, msg) {
  var f, obj = {
    evidenceList: jspb.Message.toObjectList(msg.getEvidenceList(),
    tendermint_types_evidence_pb.Evidence.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tendermint.evidence.List}
 */
proto.tendermint.evidence.List.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tendermint.evidence.List;
  return proto.tendermint.evidence.List.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tendermint.evidence.List} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tendermint.evidence.List}
 */
proto.tendermint.evidence.List.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new tendermint_types_evidence_pb.Evidence;
      reader.readMessage(value,tendermint_types_evidence_pb.Evidence.deserializeBinaryFromReader);
      msg.addEvidence(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tendermint.evidence.List.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tendermint.evidence.List.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tendermint.evidence.List} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tendermint.evidence.List.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEvidenceList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      tendermint_types_evidence_pb.Evidence.serializeBinaryToWriter
    );
  }
};


/**
 * repeated tendermint.types.Evidence evidence = 1;
 * @return {!Array<!proto.tendermint.types.Evidence>}
 */
proto.tendermint.evidence.List.prototype.getEvidenceList = function() {
  return /** @type{!Array<!proto.tendermint.types.Evidence>} */ (
    jspb.Message.getRepeatedWrapperField(this, tendermint_types_evidence_pb.Evidence, 1));
};


/**
 * @param {!Array<!proto.tendermint.types.Evidence>} value
 * @return {!proto.tendermint.evidence.List} returns this
*/
proto.tendermint.evidence.List.prototype.setEvidenceList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.tendermint.types.Evidence=} opt_value
 * @param {number=} opt_index
 * @return {!proto.tendermint.types.Evidence}
 */
proto.tendermint.evidence.List.prototype.addEvidence = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.tendermint.types.Evidence, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.tendermint.evidence.List} returns this
 */
proto.tendermint.evidence.List.prototype.clearEvidenceList = function() {
  return this.setEvidenceList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.tendermint.evidence.Info.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tendermint.evidence.Info.prototype.toObject = function(opt_includeInstance) {
  return proto.tendermint.evidence.Info.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tendermint.evidence.Info} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tendermint.evidence.Info.toObject = function(includeInstance, msg) {
  var f, obj = {
    evidence: (f = msg.getEvidence()) && tendermint_types_evidence_pb.Evidence.toObject(includeInstance, f),
    time: (f = msg.getTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    validatorsList: jspb.Message.toObjectList(msg.getValidatorsList(),
    tendermint_types_validator_pb.Validator.toObject, includeInstance),
    totalVotingPower: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tendermint.evidence.Info}
 */
proto.tendermint.evidence.Info.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tendermint.evidence.Info;
  return proto.tendermint.evidence.Info.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tendermint.evidence.Info} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tendermint.evidence.Info}
 */
proto.tendermint.evidence.Info.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new tendermint_types_evidence_pb.Evidence;
      reader.readMessage(value,tendermint_types_evidence_pb.Evidence.deserializeBinaryFromReader);
      msg.setEvidence(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTime(value);
      break;
    case 3:
      var value = new tendermint_types_validator_pb.Validator;
      reader.readMessage(value,tendermint_types_validator_pb.Validator.deserializeBinaryFromReader);
      msg.addValidators(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTotalVotingPower(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tendermint.evidence.Info.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tendermint.evidence.Info.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tendermint.evidence.Info} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tendermint.evidence.Info.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEvidence();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      tendermint_types_evidence_pb.Evidence.serializeBinaryToWriter
    );
  }
  f = message.getTime();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getValidatorsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      tendermint_types_validator_pb.Validator.serializeBinaryToWriter
    );
  }
  f = message.getTotalVotingPower();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
};


/**
 * optional tendermint.types.Evidence evidence = 1;
 * @return {?proto.tendermint.types.Evidence}
 */
proto.tendermint.evidence.Info.prototype.getEvidence = function() {
  return /** @type{?proto.tendermint.types.Evidence} */ (
    jspb.Message.getWrapperField(this, tendermint_types_evidence_pb.Evidence, 1));
};


/**
 * @param {?proto.tendermint.types.Evidence|undefined} value
 * @return {!proto.tendermint.evidence.Info} returns this
*/
proto.tendermint.evidence.Info.prototype.setEvidence = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tendermint.evidence.Info} returns this
 */
proto.tendermint.evidence.Info.prototype.clearEvidence = function() {
  return this.setEvidence(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tendermint.evidence.Info.prototype.hasEvidence = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Timestamp time = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.tendermint.evidence.Info.prototype.getTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.tendermint.evidence.Info} returns this
*/
proto.tendermint.evidence.Info.prototype.setTime = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tendermint.evidence.Info} returns this
 */
proto.tendermint.evidence.Info.prototype.clearTime = function() {
  return this.setTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tendermint.evidence.Info.prototype.hasTime = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated tendermint.types.Validator validators = 3;
 * @return {!Array<!proto.tendermint.types.Validator>}
 */
proto.tendermint.evidence.Info.prototype.getValidatorsList = function() {
  return /** @type{!Array<!proto.tendermint.types.Validator>} */ (
    jspb.Message.getRepeatedWrapperField(this, tendermint_types_validator_pb.Validator, 3));
};


/**
 * @param {!Array<!proto.tendermint.types.Validator>} value
 * @return {!proto.tendermint.evidence.Info} returns this
*/
proto.tendermint.evidence.Info.prototype.setValidatorsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.tendermint.types.Validator=} opt_value
 * @param {number=} opt_index
 * @return {!proto.tendermint.types.Validator}
 */
proto.tendermint.evidence.Info.prototype.addValidators = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.tendermint.types.Validator, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.tendermint.evidence.Info} returns this
 */
proto.tendermint.evidence.Info.prototype.clearValidatorsList = function() {
  return this.setValidatorsList([]);
};


/**
 * optional int64 total_voting_power = 4;
 * @return {number}
 */
proto.tendermint.evidence.Info.prototype.getTotalVotingPower = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.tendermint.evidence.Info} returns this
 */
proto.tendermint.evidence.Info.prototype.setTotalVotingPower = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


goog.object.extend(exports, proto.tendermint.evidence);
