name: goreleaser

on:
  push:
    branches:
      - "release/*"
    tags:
      - "v*.*.*"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.1
      - name: release dry run
        run: make release-dry-run
      - name: setup release environment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' > .release-env
      - name: release publish
        run: make release

  goreleasermacm1:
    runs-on: macos-latest
    env:
      RA_TARGET: aarch64-apple-darwin
      SELECT_XCODE: /Applications/Xcode_12.2.app

    steps:
      - name: Select XCode version
        run: sudo xcode-select -s "${SELECT_XCODE}"
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: display sdk
        run: SDKROOT=$(xcrun -sdk macosx11.0 --show-sdk-path) MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx11.0 --show-sdk-platform-version)  && echo $SDKROOT  . " , " . $MACOSX_DEPLOYMENT_TARGET
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.1'
      - name: release dry run
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: -f ./.goreleasermac.yml --rm-dist --skip-validate  --skip-publish   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: setup release environment
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release -f ./.goreleasermac.yml --rm-dist --skip-validate   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}