name: goreleaser

on:
  push:
    branches:
      - "release/*"
    tags:
      - "v*.*.*"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.1
      - name: release dry run
        run: make release-dry-run
      - name: setup release environment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' > .release-env
      - name: release publish
        run: make release

  goreleasermacm1:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.0'          
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.1'
      - name: release dry run
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: -f ./.goreleasermac.yml --rm-dist --skip-validate  --skip-publish   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: setup release environment
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release -f ./.goreleasermac.yml --rm-dist --skip-validate   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}