name: Build

on:
  push:
    branches:
      - master
      - release/**
      - test

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.1
      - name: Normal check out code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set GOBIN
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: show info
        run: |
          echo $Env:GITHUB_WORKSPACE  "github workspace"
      - name: buildwindows
        run: |
          cd
          dir
          makewin.bat
